[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.run]
# Run makes no sense for a library. So we overwrite it with an empty echo.
# Building is also not necessary, because it gets build as dependency by the
# client and server code.
command = "echo"
args = [""]
dependencies = []

[tasks.rpi-release]
# For the com lib, we don't need to do anything for release mode.
# Explicitly building is not necessary, because it gets build as dependency by the
# client and server code.
command = "echo"
args = [""]
dependencies = []
