[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["build"]

[tasks.run]
# Run makes no sense for a library. So we overwrite it with an empty echo.
# We don't need to build the library here, because the `run` step has `build` as a dependency.
# TODO (Wybe 2024-01-02): There should be a better way than making this "echo"
command = "echo"
args = [""]
dependencies = ["build"]
