[package]
name = "rss_r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rss_com_lib = { path = "rss_com_lib" }

actix-web = { version = "4", features = ["rustls"] }
actix-web-lab = "0.16.4"
actix-files = "0.6.1"
actix-identity = "0.4.0"

feed-rs = "1.1"
log = "0.4.17"
simplelog = "0.12.0"
rustls = "0.20.6"
rustls-pemfile = "1.0.0"
thiserror = "1.0.31"
reqwest = "0.11.11"
ron = "0.7"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"

[dev-dependencies]
pretty_assertions = "1.3.0"

[profile.release]
opt-level = 2 # fast and small wasm

[workspace]
members = [
    "rss_r_web"
]