[env]
TARGET_TRIPLE = "wasm32-unknown-unknown"
WASM_TARGET_DIR = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/${TARGET_TRIPLE}/debug/"

[tasks.install-rustup-target-wasm32]
command = "rustup"
args = ["target", "add", "${TARGET_TRIPLE}"]

[tasks.install-trunk]
install_crate = { crate_name = "trunk" }

[tasks.build]
command = "trunk"
args = ["build"]
dependencies = ["install-rustup-target-wasm32", "install-trunk", "format"]

[tasks.run]
# Run makes no sense for a library. So we overwrite it with an empty echo.
# We don't need to build the library here, because the `run` step has `build` as a dependency.
# TODO (Wybe 2022-07-10): There should be a better way than making this "echo"
command = "echo"
args = [""]
dependencies = ["build"]

[tasks.rpi-release]
command = "trunk"
args = ["build", "--release"]
dependencies = ["install-rustup-target-wasm32", "install-trunk"]
